### ISSUE TITLE
3 John is named 1 John in `ron-rccv.usfx.xml`

### ISSUE THREAD

**Issue by SebastianNechita** [seven1m/open-bibles#11]
Firstly, thank you for offering all these bibles for us. 😄 

The issue I want to report is in `ron-rccv.usfx.xml`. The header is wrong for one of the books, namely for `3 Ioan` or 3 John. In the file from the repo it appears as `1 Ioan`. 

You can search for `1 Ioan` and you will see that it's duplicated. The second occurrence should be `3 Ioan` :D

Thanks! 
Sebi

**Comment by seven1m** [comment]
Thanks for letting me know!
