### ISSUE TITLE
Philemon returns Philippians

### ISSUE THREAD

**Issue by DannyFGitHub** [seven1m/open-bibles#18]
Searching for Philemon returns Philippians

Requesting:
https://bible-api.com/Philemon+1:1

Returns:

reference | "Philippians 1:1"
-- | --
verses |  
0 |  
book_id | "PHP"
book_name | "Philippians"
chapter | 1
verse | 1
text | "Paul and Timothy, servants of Jesus Christ;\nTo all the saints in Christ Jesus who are at Philippi, with the overseers\n and servants:\n"
text | "Paul and Timothy, servants of Jesus Christ;\nTo all the saints in Christ Jesus who are at Philippi, with the overseers\n and servants:\n"
translation_id | "web"
translation_name | "World English Bible"
translation_note | "Public Domain"

What might I be doing wrong or how to change query to make Philemon work?

**Comment by VladimirSlvl** [comment]
Good afternoon, when will it be possible to see the Russian synodal translation in api?

**Comment by seven1m** [comment]
This was fixed here: https://github.com/seven1m/bible_ref/commit/a597b68341032e45d53c8f59ce10e8a39c85727e
