### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by codingmaye** [seven1m/open-bibles#19]
Hey dear,

I really love your work. I'm interested in using the api to fetch Spanish version of the Bible, especially the RV1909. But it doesn't work. Neither any other version from Spanish does.

I have tried to rewrite the URL from my browser a countless of time without success.

How can I get spanish version of the Bible from your API?

Have a nice day 😄

**Comment by seven1m** [comment]
I don't know how to address this. We need a freely licensed bible XML file.
