### ISSUE TITLE
Chinese Union Version 1919

### ISSUE THREAD

**Issue by danzuep** [seven1m/open-bibles#21]
> When adding a new bible translation to this repo, please link to the source where you obtained the file. If it's not obvious from the linked source, please also link to the license for the bible translation so we can ensure it is available for distribution. Thanks!

Thanks for hosting this project Tim. I started a "just for fun" [BibleApp](https://github.com/danzuep/BibleApp) project three days ago, but I would like to add the [CUV bible](https://en.wikipedia.org/wiki/Chinese_Union_Version) which is now [in the public domain](https://www.biblegateway.com/versions/Chinese-Union-Version-Traditional-CUV/). [Here's a link](https://www.ph4.org/_dl.php?back=bbl&a=Bible_Chinese_CUV_Strong&b=zefania&c) to an xml version I found online, does it matter that it's in a different format from yours? I can manually add some info to the file if you want, then I can do a pull request.

I'm wanting to use it for a simple cross-platform open source .NET Cantonese to Jyutping romanisation/translation app, but so far the app is only showing an English bible (KJV).

This is useful: https://hackathon.bible/data/

**Comment by seven1m** [comment]
Very cool! I think the XML format you linked is Zefania, and we already have some Zefania-format files in the repo, so that's great! If you want to make a PR with that file, that seems like a good next move. Be sure to update the README with details about the version.

Thanks!

**Comment by danzuep** [comment]
I found this goldmine of [Zefania](https://de.wikipedia.org/wiki/Zefania_XML) bibles: https://github.com/kohelet-net-admin/zefania-xml-bibles/tree/master/Bibles

My goal was to have a web endpoint where I could download different public domain versions from, and as this was all I was wanting I'll close this ticket.

The basic bible app MVP is done, but it's going to be a more work than I thought to get the romanisation working as the best transliteration libraries are written in python. I'll post a link here once it's on [F-Droid](https://f-droid.org/en/).
